import createDOMPurify, {type Config, type DOMPurify, type WindowLike} from "dompurify";

const ALLOWED_TAGS = [
  "a",
  "abbr",
  "b",
  "blockquote",
  "br",
  "code",
  "dd",
  "defs",
  "del",
  "details",
  "desc",
  "div",
  "dl",
  "dt",
  "em",
  "figcaption",
  "figure",
  "g",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "img",
  "kbd",
  "li",
  "line",
  "linearGradient",
  "mark",
  "marker",
  "ol",
  "p",
  "path",
  "polygon",
  "polyline",
  "pre",
  "q",
  "rect",
  "rp",
  "rt",
  "ruby",
  "s",
  "section",
  "small",
  "source",
  "span",
  "stop",
  "strong",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "text",
  "textPath",
  "tfoot",
  "th",
  "thead",
  "tr",
  "tspan",
  "u",
  "ul",
  "title",
  "video",
];

const GLOBAL_ATTRIBUTES = [
  "class",
  "data-line",
  "data-mermaid-source",
  "data-tool",
  "id",
  "role",
  "style",
  "title",
  "aria-current",
  "aria-describedby",
  "aria-expanded",
  "aria-hidden",
  "aria-label",
  "aria-labelledby",
  "aria-selected",
];

const SANITIZE_CONFIG: Config = {
  ALLOWED_TAGS,
  ALLOWED_ATTR: [
    ...GLOBAL_ATTRIBUTES,
    "align",
    "alt",
    "aria-roledescription",
    "cx",
    "cy",
    "d",
    "colspan",
    "controls",
    "dominant-baseline",
    "fill",
    "font-family",
    "font-size",
    "font-style",
    "font-weight",
    "height",
    "href",
    "marker-end",
    "markerHeight",
    "markerUnits",
    "markerWidth",
    "loading",
    "name",
    "offset",
    "orient",
    "poster",
    "points",
    "preserveAspectRatio",
    "refX",
    "refY",
    "rel",
    "rowspan",
    "rx",
    "ry",
    "src",
    "start",
    "stroke",
    "stroke-dasharray",
    "stroke-linecap",
    "stroke-width",
    "text-anchor",
    "target",
    "transform",
    "type",
    "viewBox",
    "width",
    "x",
    "x1",
    "x2",
    "y",
    "y1",
    "y2",
  ],
  ADD_DATA_URI_TAGS: ["img", "source", "video"],
  ALLOW_ARIA_ATTR: true,
  ALLOW_DATA_ATTR: false,
  ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel|data|blob|wximg):|\/\/|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
  FORBID_TAGS: ["script", "style"],
};

const purifier = createPurifier();

export function sanitizeRenderedHtml(html: string): string {
  return purifier.sanitize(html, SANITIZE_CONFIG);
}

function createPurifier(): DOMPurify {
  const root = globalThis.window as WindowLike | undefined;
  if (!root) {
    throw new Error("DOMPurify requires a browser-like window before rendering Markdown.");
  }
  return createDOMPurify(root);
}
